title: Jekyll Theme Primer
description: Primer is a Jekyll theme for GitHub Pages

remote_theme: pages-themes/primer
repository: pages-themes/primer

github:
    private: false
    license:
        name: MIT
    source:
        branch: "master"
        path: "/"
    repository_url: "https://github.com/pages-themes/primer"

exclude:
    - node_modules
    - script

sass:
    style: compressed

plugins:
    - html-proofer
    - rubocop-github
    - w3c_validators
    - webrick
    - jekyll
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-theme-primer
    - jekyll-include-cache
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-github-metadata
    - jekyll-gist
